sudo: required

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
  
matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - sudo apt-get install ant
    - sudo apt-get install tclsh
    - sudo apt install default-jre
    - sudo apt-get install swig
    - sudo apt-get install google-perftools
    - sudo apt-get install libgoogle-perftools-dev
    - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
    - sudo apt-get update -q
    - sudo apt-get install python3.6
    - sudo apt-get install python3.6-dev
    - eval "${MATRIX_EVAL}"
    - export CXX=/usr/local/bin/g++
    - export CC=/usr/local/bin/gcc
    - export LD_LIBRARY_PATH=/usr/local/lib64/:/usr/lib64/:$LD_LIBRARY_PATH
    - export PATH=/usr/local/bin/:$PATH


install:

# Build steps
script:
  - make release
  
